import Header from "@/app/components/Header";
import { Lateef } from "next/font/google";
import "./globals.css";

// import lateef font
const lateef = Lateef({
  subsets: ["latin"],
  weight: ["200", "300", "400"],
  variable: "--font-lateef",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lateef.variable}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
